version: '3.11'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: project3a_scrum12
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"
